name: CI

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}

    steps:
      - uses: actions/checkout@v7
      - name: pack.mcmeta
        run: |
          GITHUB_SHA=$(git rev-parse --short ${{ github.sha }})
          GITHUB_REF_NAME=$(echo ${{ github.ref_type == 'tag' && github.ref_name || 'dev' }})
          tmp="$(mktemp)"
          envsubst '${GITHUB_SHA},${GITHUB_REF_NAME}' <pack.mcmeta >"$tmp" && mv "$tmp" pack.mcmeta

      - name: Upload
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: ImperiumMC Resource Pack
          path: |
            assets/
            pack.mcmeta
            pack.png
          if-no-files-found: error

  release:
    name: Release
    needs: build
    if: ${{ github.ref_type == 'tag' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.build.outputs.artifact-id }}
          skip-decompress: true

      - name: List files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: ImperiumMC ${{ github.ref_name }}
          files: ImperiumMC.zip
          prerelease: true
          fail_on_unmatched_files: true
          generate_release_notes: true
