name: CI

on: [push, workflow_dispatch]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Zip
        run: |
          GITHUB_SHA=$(git rev-parse --short ${{ github.sha }})
          tmp="$(mktemp)"
          envsubst '${GITHUB_SHA}' <pack.mcmeta >"$tmp" && mv "$tmp" pack.mcmeta
          zip -r "ImperiumMC.zip" assets/ pack.mcmeta pack.png

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ImperiumMC Resource Pack
          path: ImperiumMC.zip
          archive: false
          if-no-files-found: error

      - name: Release
        uses: softprops/action-gh-release@v3
        if: ${{ github.ref_type == 'tag' || github.event_name == 'workflow_dispatch' }}
        with:
          name: ImperiumMC ${{ github.ref_name }}
          files: ImperiumMC.zip
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
